// Generated by Unloop
// Weather Station

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_refresh_clicked(|| {
        println!("refresh clicked");
    });
    
    app.on_forecast_clicked(|| {
        println!("forecast clicked");
    });
    
    app.on_export_clicked(|| {
        println!("export clicked");
    });
    

    
    app.run()
}
