// Generated Data Model

export struct AppData {
    current-temp: float,
    feels-like: float,
    humidity: float,
    pressure: float,
    wind-speed: float,
    wind-direction: float,
    rain-today: float,
    uv-index: float,
    sensor-status: string,
    wifi-status: string,
    temp-unit: string,
    wind-unit: string,
    pressure-unit: string,
    update-interval: string,
    data-logging: bool,
    brightness: float,
    version: string,
}
